### ISSUE TITLE
404 Error in AWS Logs: Unhandled Promise Rejection

### ISSUE THREAD

**Issue by levellers** [MarkusGalant/chatgpt-slackbot-serverless#2]
2023-02-16T11:42:01.764+11:00Copy2023-02-16T00:42:01.764Z	1f67eff4-2749-4ac9-bf2e-8b9575264edf	ERROR	Unhandled Promise Rejection 	{     "errorType": "Runtime.UnhandledPromiseRejection",     "errorMessage": "Error: ChatGPT error 404",     "reason": {         "errorType": "Error",         "errorMessage": "ChatGPT error 404",         "statusCode": 404,         "statusText": "Not Found",         "stack": [             "Error: ChatGPT error 404",             "    at fetchSSE (file:///var/task/node_modules/chatgpt/build/index.js:43:19)",             "    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)"         ]     },     "promise": {},     "stack": [         "Runtime.UnhandledPromiseRejection: Error: ChatGPT error 404",         "    at process.<anonymous> (file:///var/runtime/index.mjs:1194:17)",         "    at process.emit (node:events:513:28)",         "    at emit (node:internal/process/promises:149:20)",         "    at processPromiseRejections (node:internal/process/promises:283:27)",         "    at process.processTicksAndRejections (node:internal/process/task_queues:96:32)"     ] }
--

**Comment by levellers** [comment]
In slack, the BOT responds with 🤔 to every prompt.

**Comment by rawiriblundell** [comment]
I have this issue as well.  Presented in markdown:

```
2023-02-17T08:48:50.550Z	08415049-39eb-41ec-b5dc-46253f3b9e1d	ERROR	Unhandled Promise Rejection 	{
    "errorType": "Runtime.UnhandledPromiseRejection",
    "errorMessage": "Error: ChatGPT error 404",
    "reason": {
        "errorType": "Error",
        "errorMessage": "ChatGPT error 404",
        "statusCode": 404,
        "statusText": "Not Found",
        "stack": [
            "Error: ChatGPT error 404",
            "    at fetchSSE (file:///var/task/node_modules/chatgpt/build/index.js:43:19)",
            "    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)"
        ]
    },
    "promise": {},
    "stack": [
        "Runtime.UnhandledPromiseRejection: Error: ChatGPT error 404",
        "    at process.<anonymous> (file:///var/runtime/index.mjs:1194:17)",
        "    at process.emit (node:events:513:28)",
        "    at emit (node:internal/process/promises:149:20)",
        "    at processPromiseRejections (node:internal/process/promises:283:27)",
        "    at process.processTicksAndRejections (node:internal/process/task_queues:96:32)"
    ]
}
```

The previous log entry to this states:

```
2023-02-17T08:48:49.956Z	08415049-39eb-41ec-b5dc-46253f3b9e1d	ERROR	(node:8) ExperimentalWarning: The Fetch API is an experimental feature. This feature could change at any time
(Use `node --trace-warnings ...` to show where the warning was created)
```

And the following one states:

```
Unknown application error occurred
Runtime.Unknown
```

**Comment by rawiriblundell** [comment]
This seems possibly related to https://github.com/transitive-bullshit/chatgpt-api/issues/311

If I change `node_modules/chatgpt/build/index.js` line 73 to read:

```
var CHATGPT_MODEL = "text-davinci-003";
```

And then redeploy, then it starts working.

It looks like I need to add an emoji for `:done:` to my Slack workspace as well, or remove that from `app.ts`.

**Comment by vaughngit** [comment]
Thank you! Fix worked for me too.
